### ISSUE TITLE
Problematic videos should be found by the backend and have an option to prune

### ISSUE THREAD

**Issue by mmetro** [mmetro/WeirdSideofYouTube#50]

**Comment by ghost** [comment]
We can use the existing getVideoInfo function in the add video function, as well as a repeating prune function using the information here: http://stackoverflow.com/questions/3899387/how-do-i-use-the-youtube-api-to-check-if-a-video-is-embeddable
https://developers.google.com/youtube/v3/getting-started

Also need to check that it is in fact a youtube URL so that the crawlers don't pick up other random posts.
